server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
  servlet:
    session:
      timeout: 30m
  shutdown: graceful

logging:
  level:
    ru.spbstu.memory.cards: DEBUG

spring:
  application:
    name: memory-cards-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:-jdbc:postgresql://localhost:5432/memory_cards}
    username: ${SPRING_DATASOURCE_USERNAME:-user}
    password: ${SPRING_DATASOURCE_PASSWORD:-password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public

management:
  endpoints:
    web:
      exposure:
        include: health,info
