name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: .

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: static-analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build project
        run: ./gradlew build -x ktlintCheck

      - name: Save build outputs
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Run tests
        run: ./gradlew test -x ktlintCheck

  quick-test:
    name: Docker Compose Health Check
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Build and start services
        run: docker compose up --build -d

      - name: Wait for health endpoint
        run: |
          for i in {1..40}; do
            if curl -fs http://localhost:8080/actuator/health > /dev/null; then
              exit 0
            fi
            sleep 3
          done
          echo "Health check failed: application did not become ready"
          docker compose logs
          exit 1

      - name: Shutdown services
        if: always()
        run: docker compose down -v

  publish:
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: quick-test
    steps:
      - uses: actions/checkout@v3
      - name: Log in
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        # if some time we need versioning, we can use tags here
        # like :${{ github.sha }} or :${{ github.ref_name }}-${{ github.sha }}
        run: docker build -t $REGISTRY/$IMAGE_NAME:latest .

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:latest
